@startuml
title 話題沸騰ポット クラス図 (検査用)

<style>
shadowing: false
monochrome: true
fontcolor: automatic
</style>

skinparam ObjectBorderColor #808080
skinparam ObjectFontColor automatic
skinparam ArrowColor #808080
skinparam linetype ortho

class "ランプ" as lamp #lightgray {
    - 点灯状態
}
class "ボタン" as button #lightcyan {
    - 押下状態
    - 有効性
}
class "インジケータセル" as cell #lightgray {
    - 表示
}

class "水位" as level {
    - 位置
    - 満水
    - 空
}

class "水位センサ" as wSenser #lightcyan {
    - 検出値
}
class "満水センサ" as wwSenser #lightcyan {
    - 検出値
}
wwSenser  --  level
wSenser "1..*" -- "1" level
cell "1..*" -- "1" level

class "蓋" as coverTop {
    - 閉
}
class "蓋センサ" as coverSenser #lightcyan {
    - 検出値
}

coverSenser  --  coverTop

class "給湯口" as operation {
    - ロック
    - 給湯中
}
class "ポンプ" as pomp #lightpink {
    - 駆動中
}

pomp  --  operation
button "1..*" -- "1" operation
lamp  --  operation

class "温度表示" as tempView #lightgray {
    - 表示
}
class "モード表示" as modeView #lightgray {
    - モード表示
}

class "温度制御" as tempCntl {
    - 制御中
    - 目標温度
    - 水温
    - 制御方式*
    - 操作量M
}
class "ヒータ" as heater #lightpink {
    - 駆動中
}
class "ヒータ用電源" as power #lightpink {
    - 駆動中
}
class "サーミスタ" as sermister #lightcyan {
    - 検出値
}
abstract class "制御方式" as method {
    ----
    +操作量導出()
}

heater  --  tempCntl
power  --  tempCntl
sermister  --  tempCntl
tempView  --  tempCntl
power ..> heater
tempCntl "1" -- "0..1" method
remove method

class "ポット" as body {
    - 現在状態*
}
class "ポット状態" as potState {
}
class "状態遷移" as transition {
    - 待機イベント
    - ガード
}
note as states
    ポットは全6つの状態を持ち,
    うち1つを現在状態として指す
end note

lamp "1..*" -- "1" body
remove potState
remove transition

class "保温モード" as keepmode {
    - モード
    - 保温温度
}

modeView -- keepmode
button "1..*" -- "1" keepmode

class "温度エラー監視" as errorWatch {
    - 検知したエラー
    - 前回水温
    - 監視中
    - 監視対象行為
    - 経過時間
}

class "ブザー" as buzzer #lightpink {
    - 駆動中
}

' ----- 相互 ----
body ..> level
operation  --  body
coverTop  --  body
errorWatch -- body
body  --  tempCntl
body  --  keepmode
errorWatch ..> tempCntl
operation ..> coverTop
keepmode ..> coverTop
body ..> buzzer
operation ..> buzzer
keepmode ..> buzzer

' ----- 配置 -----

legend bottom left
    1対1の多重度表記のみ, その数値を省略
endlegend
@enduml
