@startuml
title 話題沸騰ポット クラス図 (検査用)

<style>
shadowing: false
monochrome: true
fontcolor: automatic
</style>

skinparam ObjectBorderColor #808080
skinparam ObjectFontColor automatic
skinparam ArrowColor #808080
skinparam linetype ortho

class "ランプ" as lamp #lightgray {
    - 点灯状態
}
class "ボタン" as button #lightcyan {
    - 押下状態
    - 有効性
}
class "インジケータセル" as cell #lightgray {
    - 表示
}

class "水位" as level {
    - 位置
    - 満水
    - 空
}

class "水位センサ" as wSenser #lightcyan {
    - 検出値
}
class "満水センサ" as wwSenser #lightcyan {
    - 検出値
}
level  --  wwSenser
level "1" *-- "4" wSenser
level "1" *-- "4" cell

class "蓋" as coverTop {
    - 閉
}
class "蓋センサ" as coverSenser #lightcyan {
    - 検出値
}

coverTop  --  coverSenser

class "給湯口" as operation {
    - ロック
    - 給湯中
}
class "ポンプ" as pomp #lightpink {
    - 駆動中
}

operation  --  pomp
operation  --  button
operation  --  lamp

class "温度/モード表示窓" as tempView #lightgray {
    - 温度表示
    - モード表示
}

class "温度制御" as tempCntl {
    - 制御中
    - 目標温度
    - 水温
    - 制御方式*
    - 操作量M
}
class "ヒータ" as heater #lightpink {
    - 駆動中
}
class "ヒータ用電源" as power #lightpink {
    - 駆動中
}
class "サーミスタ" as sermister #lightcyan {
    - 検出値
}
abstract class "制御方式" as method {
    ----
    +操作量導出()
}

tempCntl  --  heater
tempCntl  --  power
tempCntl  --  tempView
tempCntl  --  sermister
tempCntl "1" -- "0..1" method
remove method

class "ポット" as body {
}
class "ポット状態" as potState {
    - 待機イベント
    - ガード
}

body "1" -- "2" button
body "1" -- "2" lamp
body  *-- potState
potState "0..*" o-- "0..*" potState
'remove potState

class "保温モード" as keepmode {
    - モード
    - 保温温度
}

keepmode -- tempView
keepmode -- button

class "検出しているエラー" as error {
    - エラー
}

class "ブザー" as buzzer #lightpink {
    - 駆動中
}

' ----- 相互 ----
level  ..  body
body  ..  operation
body  ..  tempCntl
coverTop  ..  body
coverTop  ..  operation
body  ..  buzzer
body .. error
tempCntl .. error
operation .. buzzer
error .. buzzer
body .. keepmode

' ----- 配置 -----

legend bottom left
    1対1の多重度表記のみ, その数値を省略
endlegend
@enduml