@startuml
title 話題沸騰ポット オブジェクト図 (給水線, 沸騰開始, 通電)

<style>
shadowing: false
monochrome: true
fontcolor: automatic
</style>

skinparam ObjectBorderColor #808080
skinparam ObjectFontColor automatic
skinparam ArrowColor #808080
skinparam linetype ortho

'#lightcyan センサ, ボタン
'#lightgray 表示
'#lightpink 駆動物

rectangle "-" as water {
object "水位" as sl {
    位置 = 4
    満水 = false
    空 = false
}

object "第1,2,3,4:水位センサ" as s1 #lightcyan {
    本当は4つ実体がある
    ===
    番号 = 1
    検出値 = on [pot-110-13]
    ----
    番号 = 2
    検出値 = on [pot-110-13]
    ----
    番号 = 3
    検出値 = on [pot-110-13]
    ----
    番号 = 4
    検出値 = on [pot-110-13]
}
object "満水センサ" as s5 #lightcyan {
    検出値 = off [pot-110-11]
}
}

rectangle "-" as cover {
object "蓋" as vm {
    閉 = true
    閉検出時間 = 3s [pot-220-11]
    開検出時間 = 1s [pot-221-11]
}
object "蓋センサ" as s6 #lightcyan {
    検出値 = on [pot-110-15, 仮定]
}
}

rectangle "-" as output {
object "給湯口" as op {
    ロック = 解除 [pot-250-11]
    給湯中 = false
}
object "ポンプ" as pp #lightpink {
    駆動中 = off
}
}

rectangle "-" as heat {
object "温度制御" as tm {
    制御中 = true
    目標温度 = 100 [pot-310]
    水温 = 25
    制御方式* = 目標温度ON/OFF方式 [pot-310-21]
    操作量M = 100% [pot-400-21]
    経過時間 = 直後から数秒程度 [仮定]
    カルキ抜き待機時間 = 3分 [pot-311-11]
    制御周期 = 定数
}
object "ヒータ" as ht #lightpink {
    駆動中 = on
    PWM = 100%
}
object "ヒータ用電源" as hp #lightpink {
    駆動中 = 給電中 [pot-110-18]
}
object "サーミスタ" as ss #lightcyan {
    検出値 = 25 (常温) [仮定]
}
object "温度エラー監視" as error {
    検知したエラー = なし
    監視中 = true
    監視対象行為 = 加熱
    前回水温 = 25
    経過時間 = 数秒
    検出周期 = 1分 [pot-500-31]
}
}

rectangle "-" as main {

object "ポット" as wm {
    現在状態* = 加熱中(沸騰行為)
}

object "加熱中(沸騰行為):ポット状態" as boil {
}

note as transition
    待機イベント => 沸点到達 [6.2]
    次状態 => カルキ抜き中(沸騰行為) [6.1, 6.3]
    ガード => なし
    待機イベント => エラー検知 [6.2]
    次状態 => エラー [6.1, 6.3]
    ガード => なし
    待機イベント => 温度制御停止 [6.2]
    次状態 => アイドル [6.1, 6.3]
    ガード => !蓋.閉 ∪ 水位.空
end note

}

rectangle "-" as keeper {
object "保温モード" as mm {
    モード = 高温モード [pot-240-11]
    保温温度 = 98 [pot-240-31]
}
}

rectangle "-" as uipanel {
object "表示部" as view
object "操作部" as panel
object "ブザー" as bz #lightpink {
    駆動中 = off
    鳴動残り時間 = 0
    鳴動残り回数 = 0
}
object "モード表示" as ms #lightgray {
    表示 = 高温 [pot-240-41]
}
object "沸騰ボタン:ボタン" as b3 #lightcyan {
    押下状態 = 開放 [仮定]
    有効性 = 無効 [pot-230-11]
    受け入れ時間 = 100ms [pot-230-11]
}
object "給湯ボタン:ボタン" as b1 #lightcyan {
    押下状態 = 開放 [仮定]
    有効性 = 無効 [pot-260-11]
    受け入れ時間 = 0ms
}
object "解除ボタン:ボタン" as b2 #lightcyan {
    押下状態 = 開放 [仮定]
    有効性 = 有効 [pot-250-21]
    受け入れ時間 = 100ms [pot-250-21]
}
object "保温設定ボタン:ボタン" as b5 #lightcyan {
    押下状態 = 開放 [仮定]
    有効性 = 有効 [pot-240-21]
    受け入れ時間 = 100ms [pot-240-21]
}
object "ロックランプ:ランプ" as ll #lightgray {
    点灯状態 = 消灯 [pot-250-11]
}
object "保温ランプ:ランプ" as kl #lightgray {
    点灯状態 = 消灯 [pot-310-11]
}
object "沸騰ランプ:ランプ" as bl #lightgray {
    点灯状態 = 点灯 [pot-310-11]
}
object "温度表示" as ts #lightgray {
    表示 = 常温 [pot-310-12]
}
object "第1,2,3,4:インジケータセル" as c1 #lightgray {
    本当は4つ実体がある
    ===
    番号 = 1 (対応第1水位センサ)
    点灯パターン = 点灯 [pot-280-21]
    点滅周期(点灯) = (利用されない)
    点滅周期(消灯) = (利用されない)
    ---
    番号 = 2 (対応第2水位センサ)
    点灯パターン = 点灯 [pot-280-21]
    点滅周期(点灯) = (利用されない)
    点滅周期(消灯) = (利用されない)
    ----
    番号 = 3 (対応第3水位センサ)
    点灯パターン = 点灯 [pot-280-21]
    点滅周期(点灯) = (利用されない)
    点滅周期(消灯) = (利用されない)
    ----
    番号 = 4 (対応第4水位センサ)
    点灯パターン = 点灯 [pot-280-21]
    点滅周期(点灯) = (利用されない)
    点滅周期(消灯) = (利用されない)
}
}

' ----- 水 -----
sl -- s1
sl -- s1
sl -- s1
sl -- s1
sl -- s5

' ----- 蓋・ロック -----
vm -- s6
op -- pp

' ----- 温度制御 -----
tm -- ht
tm -- hp
tm -- ss
ht <.. hp : 電力の供給

' ----- モード -----

' ----- ポット本体 -----
wm -- boil
boil .. transition
' ----- 表示部 -----
view -- c1
view -- c1
view -- c1
view -- c1
view -- ll
view -- kl
view -- bl
view -- ms
view -- ts

' ----- 操作部 -----
panel -- b1
panel -- b2
panel -- b3
panel -- b5
panel -- bz

' ----- 相互 ----
sl -- wm
sl -- view
wm -- op
wm -- tm
vm -- wm
wm -- mm
tm -- error
wm -- error
wm -- panel
wm -- view
mm -- view
tm -- view

' ----- 配置 -----
water --d[hidden]-- main
water --r[hidden]-- output
heat --d[hidden]-- main
@enduml
