@startuml
title 話題沸騰ポット オブジェクト図 (節約保温, 給湯中, 通電)

<style>
shadowing: false
monochrome: true
fontcolor: automatic
</style>

skinparam ObjectBorderColor #808080
skinparam ObjectFontColor automatic
skinparam ArrowColor #808080
skinparam linetype ortho

'#lightcyan センサ, ボタン
'#lightgray 表示
'#lightpink 駆動物

rectangle "-" as water {
object "水位" as sl {
    位置 = 2
    満水 = false
    空 = false
}

object "第1,2,3,4:第n水位センサ" as s1 #lightcyan {
    本当は4つ実体がある
    ===
    番号 = 1
    検出値 = on [pot-110-13]
    ----
    番号 = 2
    検出値 = on [pot-110-13]
    ----
    番号 = 3
    検出値 = off [pot-110-13]
    ----
    番号 = 4
    検出値 = off [pot-110-13]
}
object "満水センサ" as s5 #lightcyan {
    検出値 = off [pot-110-11]
}
object "第1,2,3,4:インジケータセル" as c1 #lightgray {
    本当は4つ実体がある
    ===
    番号 = 1 (対応第1水位センサ)
    表示 = 点灯 [pot-280-21]
    ---
    番号 = 2 (対応第2水位センサ)
    表示 = 点灯 [pot-280-21]
    ----
    番号 = 3 (対応第3水位センサ)
    表示 = 消灯 [pot-280-21]
    ----
    番号 = 4 (対応第4水位センサ)
    表示 = 消灯 [pot-280-21]
}
}

rectangle "-" as cover {
object "蓋" as vm {
    閉 = true
}
object "蓋センサ" as s6 #lightcyan {
    検出値 = on [pot-110-15, 仮定]
}
note as delay
    蓋センサ off: 1s, on: 3s [pot-220-11, pot-221-11]
end note
}

rectangle "-" as output {
object "給湯口" as op {
    ロック = 解除 [pot-250-11]
    給湯中 = true
}
object "解除ボタン:ボタン" as b2 #lightcyan {
    押下 = 開放 [仮定]
    有効性 = 無効 [pot-250-31]
}
object "ポンプ" as pp #lightpink {
    駆動中 = on
}
object "ロックランプ:ランプ" as ll #lightgray {
    表示 = 消灯 [pot-250-11]
}
}

rectangle "-" as heat {
object "温度制御" as tm {
    制御中 = true
    目標温度 = 90 [pot-240-31]
    水温 = 89
    制御方式* = PID制御方式 [pot-310-21]
    操作量M = 20% [pot-400-31, 仮定]
}
object "ヒータ" as ht #lightpink {
    駆動中 = 20% 
}
object "ヒータ用電源" as hp #lightpink {
    駆動中 = 給電中 [pot-110-18]
}
object "温度表示" as ts #lightgray {
    表示 = 89 [pot-310-12]
}
object "サーミスタ" as ss #lightcyan {
    検出値 = 89 [仮定]
}
}

rectangle "-" as main {

object "ポット" as wm {
    検知しているエラー = なし
    ポット状態* = 給湯中(保温行為)
    保温モード = 節約モード [pot-240-31, 仮定]
}
note as boil
    給湯中(保温行為):ポット状態 [6.1]

    待機イベント = 給湯要求解除 [6.2]
    次状態 => 保温(保温行為) [6.1, 6.3]
    ガード = なし

    待機イベント => エラー検知 [6.2]
    次状態 => エラー [6.1, 6.3]
    ガード => なし

    待機イベント => 温度制御停止 [6.2]
    次状態 => アイドル [6.1, 6.3]
    ガード => !蓋.閉 ∪ 水位.空
end note
object "モード表示" as ms #lightgray {
    表示 = 節約 [pot-240-41]
}
object "保温設定ボタン:ボタン" as b5 #lightcyan {
    押下 = 開放 [仮定]
    有効性 = 許可 [pot-240-21]
}
object "保温ランプ:ランプ" as kl #lightgray {
    表示 = 点灯 [pot-310-11]
}
object "沸騰ランプ:ランプ" as bl #lightgray {
    表示 = 消灯 [pot-310-11]
}
object "給湯ボタン:ボタン" as b1 #lightcyan {
    押下 = してる [仮定]
    有効性 = 許可 [pot-240-21]
}
object "沸騰ボタン:ボタン" as b3 #lightcyan {
    押下 = 開放 [仮定]
    有効性 = 無効 [pot-230-11]
}
object "ブザー" as bz #lightpink {
    駆動中 = off
}
}

' ----- 水 -----
sl -- s1
sl -- s1
sl -- s1
sl -- s1
sl -- s5

sl -- c1
sl -- c1
sl -- c1
sl -- c1

' ----- 蓋・ロック -----
vm -- s6
ll -- op
op -- pp
op -- b2

' ----- 温度制御 -----
tm -- ht
tm -- hp
tm -- ss
tm -- ts
ht <.. hp : 電力の供給

' ----- ポット本体 -----
wm -- b1
wm -- b3
wm -- kl
wm -- bl
wm -- ms
wm -- b5
wm -- bz

' ----- 相互 ----
sl -- wm
wm -- op
wm -- tm
vm -- wm
vm -- op

' ----- 配置 -----
water --d[hidden]-- main
water --r[hidden]-- output
heat --d[hidden]-- main

@enduml