@startuml
title 話題沸騰ポット オブジェクト図 (水無し, 蓋閉じてる, 通電)

<style>
shadowing: false
monochrome: true
fontcolor: automatic
</style>

skinparam ObjectBorderColor #808080
skinparam ObjectFontColor automatic
skinparam ArrowColor #808080
skinparam linetype ortho

'#lightcyan センサ, ボタン
'#lightgray 表示
'#lightpink 駆動物

object "第1,2,3,4:第n水位センサ" as s1 #lightcyan {
    本当は4つ実体がある
    ===
    番号 = 1
    検出値 = off [pot-110-13]
    ----
    番号 = 2
    検出値 = off [pot-110-13]
    ----
    番号 = 3
    検出値 = off [pot-110-13]
    ----
    番号 = 4
    検出値 = off [pot-110-13]
}
object "満水センサ" as s5 #lightcyan {
    検出値 = off [pot-110-11]
}
object "第1,2,3,4:インジケータセル" as c1 #lightgray {
    本当は4つ実体がある
    ===
    番号 = 1 (対応第1水位センサ)
    表示 = 空パターン [pot-280-41]
    ---
    番号 = 2 (対応第2水位センサ)
    表示 = 空パターン [pot-280-41]
    ----
    番号 = 3 (対応第3水位センサ)
    表示 = 空パターン [pot-280-41]
    ----
    番号 = 4 (対応第4水位センサ)
    表示 = 空パターン [pot-280-41]
}
object "水位メータ" as lm #lightgray {
    表示対象 = ポット内の水量 [pot-280]
    構成 = 水位センサと同数のインジケータセル [pot-120-11]
}

object "蓋センサ" as s6 #lightcyan {
    検出値 = on [pot-110-15, 仮定]
}
note as delay
    蓋センサ off: 1s, on: 3s [pot-220-11, pot-221-11]
end note

object "給湯口" as op {
    ロック = 解除 [pot-250-11]
    給湯中 = false
}
object "解除ボタン:ボタン" as b2 #lightcyan {
    押下 = 開放 [仮定]
    有効性 = 許可 [pot-250-21]
}
object "ポンプ" as pp #lightpink {
    駆動中 = off
}
object "ロックランプ:ランプ" as ll #lightgray {
    表示 = 消灯 [pot-250-11]
}

object "ヒータ" as ht #lightpink {
    駆動中 = 0%
}
object "ヒータ用電源" as hp #lightpink {
    駆動中 = 給電中 [pot-110-18]
}
object "コンセント" as ac {
    接続 = 差し込み中 [pot-210]
}
object "温度/モード表示窓" as ts #lightgray {
    温度表示 = なし [pot-330-42]
    モード表示 = 高温 [pot-240-41]
}
object "サーミスタ" as ss #lightcyan {
    検出値 = 室温 [仮定]
}

object "ポット" as wm {
    検知しているエラー = なし
}
object "保温設定ボタン:ボタン" as b5 #lightcyan {
    押下 = 開放 [仮定]
    有効性 = 許可 [pot-240-21]
}
object "保温ランプ:ランプ" as kl #lightgray {
    表示 = 消灯 [pot-330-41]
}
object "沸騰ランプ:ランプ" as bl #lightgray {
    表示 = 消灯 [pot-330-41]
}
object "給湯ボタン:ボタン" as b1 #lightcyan {
    押下 = 開放 [仮定]
    有効性 = 無効 [pot-260-11]
}
object "沸騰ボタン:ボタン" as b3 #lightcyan {
    押下 = 開放 [仮定]
    有効性 = 無効 [pot-230-11]
}
object "ブザー" as bz #lightpink {
    駆動中 = off
}

s1 -- lm
s1 -- c1
s1 -- c1
s1 -- c1
s1 -- c1
s5 -- c1
s5 -- lm
lm -- c1
s6 -- s5
s6 -- s1
s6 -- wm
s6 -- c1

s6 -- op
s6 -- ll

wm -- b3
bz -- b3

b5 -- s6
b5 -- ts
b5 -- bz

op -- b2
b2 -- ll

b1 -- pp
pp -- s6
pp -- op
pp -- s6
pp -- s1
pp -- ss
pp -- hp
pp -- ts

wm -- kl
wm -- bl
wm -- ht
wm -- s6
ss -- ht
ss -- ts
ss -- wm
ac -- wm
ac -- hp
ht -- bz
ht <.. hp : 電力の供給

@enduml

