#!/usr/bin/env python3
"""Convert the pot requirement spec xlsx into grep-able text + extracted images.

Regenerate docs/spec/ after 話題沸騰ポット要求仕様書.xlsx changes:

    python3 scripts/convert_spec.py

The xlsx remains the source of truth (see its 改訂履歴 sheet); files under
docs/spec/ are generated output and should not be hand-edited.
"""
import datetime
import glob
import re
import zipfile
from pathlib import Path

import openpyxl

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "docs" / "spec"
IMAGES_DIR = OUT_DIR / "images"

SHEET_ORDER = [
    "表紙",
    "改訂履歴",
    "ハードウエア構成とハードウエア要求仕様",
    "要求仕様",
    "状態遷移",
]

HEADER = (
    "# Generated by scripts/convert_spec.py from {source} - do not edit by hand.\n"
    "# Regenerate: python3 scripts/convert_spec.py\n\n"
)


def xlsx_path():
    matches = glob.glob(str(REPO_ROOT / "*.xlsx"))
    if not matches:
        raise SystemExit("no .xlsx file found in repo root")
    return matches[0]


def extract_images(zf):
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    names = [n for n in zf.namelist() if n.startswith("xl/media/")]
    for name in names:
        (IMAGES_DIR / Path(name).name).write_bytes(zf.read(name))
    return len(names)


def figure_cell_map(zf):
    """Map cell coordinate -> imageN.png for in-cell "rich value" figure cells.

    要求仕様 embeds its figures (timing charts, the PID formula, control-cycle
    diagrams) as in-cell images rather than drawing anchors, so openpyxl reads
    them back as the literal string "#VALUE!". Each such cell carries a vm=N
    attribute in xl/worksheets/sheet4.xml; those indices are assigned in
    document order and line up 1:1 with image1.png..imageN.png for this
    workbook (cross-checked against xl/richData/richValueRel.xml and
    xl/metadata.xml, which chain vm -> valueMetadata -> rich-value index ->
    richValueRel rId -> media file in that same order).
    """
    xml = zf.read("xl/worksheets/sheet4.xml").decode("utf-8")
    return {
        m.group(1): f"image{m.group(2)}.png"
        for m in re.finditer(r'<c r="([A-Z]+\d+)"[^>]*\bvm="(\d+)"', xml)
    }


def cell_text(value):
    if isinstance(value, datetime.datetime):
        return value.date().isoformat()
    return str(value)


def dump_sheet(ws, image_map):
    lines = []
    for row in ws.iter_rows():
        cells = []
        for c in row:
            if c.value is None:
                continue
            if c.coordinate in image_map:
                cells.append(f"{c.coordinate}:[FIGURE images/{image_map[c.coordinate]}]")
            else:
                cells.append(f"{c.coordinate}:{cell_text(c.value)}")
        if cells:
            lines.append(" | ".join(cells))
    if not lines:
        lines.append("(no cells - drawing/diagram only; see docs/spec/images/)")
    return "\n".join(lines) + "\n"


def main():
    path = xlsx_path()
    wb = openpyxl.load_workbook(path, data_only=True)
    with zipfile.ZipFile(path) as zf:
        n_images = extract_images(zf)
        image_map = figure_cell_map(zf)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in SHEET_ORDER:
        ws = wb[name]
        body = dump_sheet(ws, image_map if name == "要求仕様" else {})
        (OUT_DIR / f"{name}.txt").write_text(
            HEADER.format(source=Path(path).name) + body, encoding="utf-8"
        )

    print(f"wrote {len(SHEET_ORDER)} sheet files and {n_images} images to {OUT_DIR}")


if __name__ == "__main__":
    main()
